plugins {
    id 'com.android.application'
}

android {
    namespace 'com.duoluoxi.reader'
    compileSdk 34

    defaultConfig {
        applicationId "com.duoluoxi.reader"
        minSdk 26
        targetSdk 34
        versionCode 9
        versionName "2.7"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}
